AWSTemplateFormatVersion: "2010-09-09"
Description: AWS CloudTrail organization trail

Parameters:
  CloudTrailLogBucketName:
    Type: String
    Description: S3 bucket name for CloudTrail logs

Resources:
  OrganizationTrail:
    Type: AWS::CloudTrail::Trail
    Properties:
      TrailName: atlas-organization-trail
      S3BucketName: !Ref CloudTrailLogBucketName
      IsLogging: true
      IsMultiRegionTrail: true
      IncludeGlobalServiceEvents: true
      EnableLogFileValidation: true
      IsOrganizationTrail: true

Outputs:
  OrganizationTrailName:
    Description: CloudTrail organization trail name
    Value: !Ref OrganizationTrail
